dashboardPage(skin = "red",
  dashboardHeader(title = "Weather Reports on Australia"),
  dashboardSidebar(
    sidebarMenu(
    menuItem(text = "Temperature", 
             tabName = "temp", 
             icon = icon("thermometer-full")),
    menuItem(text = "Rainfall", 
              tabName = "rainy", 
              icon = icon("tint")),
    menuItem(text = "Fire", 
              tabName = "fire", 
              icon = icon("fire")))),
  dashboardBody(
    tabItems(
      tabItem(tabName = "temp",
              fluidRow(
                box(width = 3, title = "Inputs", background = "black", height = "300px", selectInput(inputId = "year1", label = "Choose a specific year or overall for overall annual trend", choices = c("Overall", unique(temp111$year))),
                       selectInput(inputId = "city", label = "Choose a city", choices = unique(temp111$city_name))),
                box(width = 9, title = "Trend of Average Min/Max Temperature", background = "red", solidHeader = TRUE, height = "450px", plotlyOutput(outputId = "plot1"))),
            fluidRow(box(width = 3, title = "Inputs", background = "black", height = "200px",
              selectInput(inputId = "year2", label = "Choose a year", choices = unique(temp3$year)),
              radioButtons(inputId = "order", label = NULL, choices= c("Ascending", "Descending"), selected = "Descending")),
              box(width = 9, title = "Cities With The Highest/Lowest Mean Temperature Based on Year", background = "red", solidHeader = TRUE, height = "450px", plotlyOutput(outputId = "plot2")))),
      tabItem(tabName = "rainy", 
        tabBox(title = "Information on Rainfall in Australia", id = "tabset1", height = "620px", width = 12,
        tabPanel("Map", selectInput(inputId = "month", label = "Choose a month", choices = unique(rain2$month)), selectInput(inputId = "year3", label = "Choose a year", choices = unique(rain2$year)), (leafletOutput(outputId = "plot3", height = "250px"))),
        tabPanel("Trend", selectInput(inputId = "year4", label = "Choose a specific year or overall for overall annual trend", choices = c("Overall", unique(rain112$year))),
                 selectInput(inputId = "cityn", label = "Choose a city", choices = unique(rain112$city_name)), plotlyOutput(outputId = "plot5")),
        tabPanel("Quality of Rainfall", selectInput(inputId = "cityname", label = "Choose a city", choices = unique(rain4$Var2)),
                 plotOutput(outputId = "plot4", height = "300px"),
                 box(width = 12, valueBoxOutput("GoodQualityBox"),
                 valueBoxOutput("PoorQualityBox"),
                 valueBoxOutput("BestCity"))),
        tabPanel("Data", h2 = ("Data Set on Rainfall"), dataTableOutput(outputId = "datarain")))),
      tabItem(tabName = "fire",
              tabBox(title = "Information on Australian Fires", id = "tabset1", height = "650px", width = 12,
                     tabPanel("Map", 
                              dateInput(inputId = "acqdate", label = "Choose a date", min = min(nasaleaf$acq_date), max = max(nasaleaf$acq_date), value = "2020-01-01"), 
                                        leafletOutput(outputId = "nasaleaf2")),
                     tabPanel("Data", dataTableOutput(outputId = "datafire")))))))
